#!/bin/bash
apt update
apt install software-properties-common -y
apt-add-repository --yes --update ppa:ansible/ansible
apt update
apt install ansible -y
apt install nginx -y
apt install python-apt -y
apt install git -y
apt install stress -y
git clone aws-autoscaling https://github.com/mihawk17490/autoscaling.git
######USE aws-autoscaling branch for testing aws autoscaling##########################
######GIVE ONLY ABOVE IN THE USER DATA FOR AMI IMAGE FOR AWS AUTOSCALING##########
#
#####GIVE BELOW IN THE LAUNCH CONFIG USERDATA#####################################
ansible-playbook /autoscaling/playbook.yaml
